Modules locales d'un module global
UdeS-STI/shelljs-nodecli pull request #1
Opened 2017-11-29 16:01 UTC by ranb2002

- [x] Refactorisation terminée
- [x] Ajout de la possibilité d'utiliser les modules locaux d'un module global
- [x] Tests unitaires
- [x] Tests fonctionnels

2017-11-29 19:09 UTC, benjaminrancourt commented
Si vous avez des suggestions pour le nom des fonctions, n'hésitez pas!

2017-11-29 19:34 UTC, katima-g33k requested changes

2017-11-29 19:34 UTC, katima-g33k commented on .babelrc
> +}
Saut de ligne

2017-11-29 19:34 UTC, katima-g33k commented on .circleci/config.yml
> +          command: npm run report-coverage
Saut de ligne

2017-11-29 19:34 UTC, katima-g33k commented on .npmignore
> +mocha.opts
Saut de ligne

2017-11-29 19:34 UTC, katima-g33k commented on src/ShellJSNodeCLI.js
> +function getBin (pkg, name) {
Nom significatif: `getBinaryFromPackage`

2017-11-29 19:34 UTC, katima-g33k commented on src/ShellJSNodeCLI.js
> +const existPackagePath = (packagePath) => {
Après avoir vu l'utilisation de cette méthode je suggère plutôt `isLocalPackage`

2017-11-29 19:34 UTC, katima-g33k commented on src/ShellJSNodeCLI.js
> +const getLocalPath = (name, root = '') => {
`getPackageLocalPath`

2017-11-29 19:34 UTC, katima-g33k commented on src/ShellJSNodeCLI.js
> +  if (isLocalPackage) {
avec mon commentaire plus haut `if (isLocalPackage(localPackagePath) {}`

2017-11-29 19:34 UTC, katima-g33k commented on src/ShellJSNodeCLI.js
> +    } else {
else inutile à cause du return. Je suis surpris que eslint ne chiale pas. Ce que je suggère pour que ça sois plus beau c'est:
```
if (!cliCommand) {
  throw
}

const args = ...
return ...
```

2017-11-29 19:34 UTC, katima-g33k commented on src/test/ShellJSNodeCLITest.js
> +
Il faut ajouter ceci:
```
beforeEach(() => {
  ShellJSNodeCLI.shell.exec.reset()
})
```

2017-11-29 19:34 UTC, katima-g33k commented on src/test/ShellJSNodeCLITest.js
> +    it("should throw an error when the Node module can't be found", () => {
Singlequotes

2017-11-29 19:50 UTC, ranb2002 commented on src/ShellJSNodeCLI.js
> +    } else {
Dans ce cas-ci, je préfères garder le positif.

2017-11-29 19:50 UTC, ranb2002 commented on .babelrc
> +}
Fait.

2017-11-29 19:50 UTC, ranb2002 commented on .circleci/config.yml
> +          command: npm run report-coverage
Fait.

2017-11-29 19:50 UTC, ranb2002 commented on .npmignore
> +mocha.opts
Fait.

2017-11-29 19:51 UTC, ranb2002 commented on src/ShellJSNodeCLI.js
> +function getBin (pkg, name) {
Fait.

2017-11-29 19:55 UTC, katima-g33k approved these changes

2017-11-30 14:28 UTC, merged

2017-11-30 14:48 UTC, Hailtothebreak reviewed
Everything seems in order